# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

repository: k-privateai/k-privateai.github.io

title: "Silicon Valley Privacy-Preserving AI Forum"
email: k.prvaite.ai@gmail.com
description: K-PAI Homepage
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "sunrise" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: US/Pacific # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : "K-PAI"
  avatar           : "/assets/images/k-on-pie.png"
  bio              : "Silicon Valley Privacy-Preserving AI Forum"
#  location         : "Silicon Valley, CA, USA"
#  email            : k.private.ai@gmail.com
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/k-privateai/k-privateai.github.io"
    - label: "Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/kpai1006/"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/company/silicon-valley-privacy-preserving-ai-forum"
    - label: "Facebook"
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/groups/1341495107592328"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:k.private.ai@gmail.com"
    - label: "Silicon Valley, CA, USA"
      icon: "fas fa-map-marker-alt"
      url: "https://maps.app.goo.gl/74sNfTckzm9aCz619"


# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/k-privateai/k-privateai.github.io"
    - label: "Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/kpai1006/"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/company/silicon-valley-privacy-preserving-ai-forum"
    - label: "Facebook"
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/groups/1341495107592328"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:k.private.ai@gmail.com"
    - label: "Silicon Valley, CA, USA"
      icon: "fas fa-map-marker-alt"
      url: "https://maps.app.goo.gl/74sNfTckzm9aCz619"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      #classes: wide
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      #classes: wide
      layout: single
      author_profile: true

category:
  type: liquid
  path: /categories/
tag:
  type: liquid
  path: /tags/
